//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUptook.LoginWSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginWSService.LoginWSService")]
    public interface LoginWSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:envialianet-LoginWSService#Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppUptook.LoginWSService.LoginResponse Login(AppUptook.LoginWSService.LoginRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:envialianet-LoginWSService#Login", ReplyAction="*")]
        System.Threading.Tasks.Task<AppUptook.LoginWSService.LoginResponse> LoginAsync(AppUptook.LoginWSService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:envialianet-LoginWSService#Login2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppUptook.LoginWSService.Login2Response Login2(AppUptook.LoginWSService.Login2Request request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:envialianet-LoginWSService#Login2", ReplyAction="*")]
        System.Threading.Tasks.Task<AppUptook.LoginWSService.Login2Response> Login2Async(AppUptook.LoginWSService.Login2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:envialianet-LoginWSService#LoginCli", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppUptook.LoginWSService.LoginCliResponse LoginCli(AppUptook.LoginWSService.LoginCliRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:envialianet-LoginWSService#LoginCli", ReplyAction="*")]
        System.Threading.Tasks.Task<AppUptook.LoginWSService.LoginCliResponse> LoginCliAsync(AppUptook.LoginWSService.LoginCliRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:envialianet-LoginWSService#LoginCli2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppUptook.LoginWSService.LoginCli2Response LoginCli2(AppUptook.LoginWSService.LoginCli2Request request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:envialianet-LoginWSService#LoginCli2", ReplyAction="*")]
        System.Threading.Tasks.Task<AppUptook.LoginWSService.LoginCli2Response> LoginCli2Async(AppUptook.LoginWSService.LoginCli2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:envialianet-LoginWSService#LoginDep", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppUptook.LoginWSService.LoginDepResponse LoginDep(AppUptook.LoginWSService.LoginDepRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:envialianet-LoginWSService#LoginDep", ReplyAction="*")]
        System.Threading.Tasks.Task<AppUptook.LoginWSService.LoginDepResponse> LoginDepAsync(AppUptook.LoginWSService.LoginDepRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:envialianet-LoginWSService#LoginDep2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppUptook.LoginWSService.LoginDep2Response LoginDep2(AppUptook.LoginWSService.LoginDep2Request request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:envialianet-LoginWSService#LoginDep2", ReplyAction="*")]
        System.Threading.Tasks.Task<AppUptook.LoginWSService.LoginDep2Response> LoginDep2Async(AppUptook.LoginWSService.LoginDep2Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class ROClientIDHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginWSService___Login", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strCod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPass;
        
        public LoginRequest() {
        }
        
        public LoginRequest(AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader, string strCod, string strPass) {
            this.ROClientIDHeader = ROClientIDHeader;
            this.strCod = strCod;
            this.strPass = strPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginWSService___LoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strNom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strCodAge;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strCodCR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string strTipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string strVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string strError;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string strSesion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string strURLDetSegEnv;
        
        public LoginResponse() {
        }
        
        public LoginResponse(AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader, bool Result, string strNom, string strCodAge, string strCodCR, string strTipo, string strVersion, string strError, string strSesion, string strURLDetSegEnv) {
            this.ROClientIDHeader = ROClientIDHeader;
            this.Result = Result;
            this.strNom = strNom;
            this.strCodAge = strCodAge;
            this.strCodCR = strCodCR;
            this.strTipo = strTipo;
            this.strVersion = strVersion;
            this.strError = strError;
            this.strSesion = strSesion;
            this.strURLDetSegEnv = strURLDetSegEnv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginWSService___Login2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Login2Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPass;
        
        public Login2Request() {
        }
        
        public Login2Request(AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader, string strUsuario, string strPass) {
            this.ROClientIDHeader = ROClientIDHeader;
            this.strUsuario = strUsuario;
            this.strPass = strPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginWSService___Login2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Login2Response {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strCod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strNom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strCodAge;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string strCodCR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string strTipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string strVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string strError;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string strSesion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string strURLDetSegEnv;
        
        public Login2Response() {
        }
        
        public Login2Response(AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader, bool Result, string strCod, string strNom, string strCodAge, string strCodCR, string strTipo, string strVersion, string strError, string strSesion, string strURLDetSegEnv) {
            this.ROClientIDHeader = ROClientIDHeader;
            this.Result = Result;
            this.strCod = strCod;
            this.strNom = strNom;
            this.strCodAge = strCodAge;
            this.strCodCR = strCodCR;
            this.strTipo = strTipo;
            this.strVersion = strVersion;
            this.strError = strError;
            this.strSesion = strSesion;
            this.strURLDetSegEnv = strURLDetSegEnv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginWSService___LoginCli", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginCliRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strCodAge;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strCod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strPass;
        
        public LoginCliRequest() {
        }
        
        public LoginCliRequest(AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader, string strCodAge, string strCod, string strPass) {
            this.ROClientIDHeader = ROClientIDHeader;
            this.strCodAge = strCodAge;
            this.strCod = strCod;
            this.strPass = strPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginWSService___LoginCliResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginCliResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strNom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strCodCR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strTipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string strVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string strError;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string strSesion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string strURLDetSegEnv;
        
        public LoginCliResponse() {
        }
        
        public LoginCliResponse(AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader, bool Result, string strNom, string strCodCR, string strTipo, string strVersion, string strError, string strSesion, string strURLDetSegEnv) {
            this.ROClientIDHeader = ROClientIDHeader;
            this.Result = Result;
            this.strNom = strNom;
            this.strCodCR = strCodCR;
            this.strTipo = strTipo;
            this.strVersion = strVersion;
            this.strError = strError;
            this.strSesion = strSesion;
            this.strURLDetSegEnv = strURLDetSegEnv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginWSService___LoginCli2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginCli2Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strCodAge;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strPass;
        
        public LoginCli2Request() {
        }
        
        public LoginCli2Request(AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader, string strCodAge, string strCliente, string strPass) {
            this.ROClientIDHeader = ROClientIDHeader;
            this.strCodAge = strCodAge;
            this.strCliente = strCliente;
            this.strPass = strPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginWSService___LoginCli2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginCli2Response {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strCodAgeOut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strCod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strNom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string strCodCR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string strTipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string strVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string strError;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string strSesion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string strURLDetSegEnv;
        
        public LoginCli2Response() {
        }
        
        public LoginCli2Response(AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader, bool Result, string strCodAgeOut, string strCod, string strNom, string strCodCR, string strTipo, string strVersion, string strError, string strSesion, string strURLDetSegEnv) {
            this.ROClientIDHeader = ROClientIDHeader;
            this.Result = Result;
            this.strCodAgeOut = strCodAgeOut;
            this.strCod = strCod;
            this.strNom = strNom;
            this.strCodCR = strCodCR;
            this.strTipo = strTipo;
            this.strVersion = strVersion;
            this.strError = strError;
            this.strSesion = strSesion;
            this.strURLDetSegEnv = strURLDetSegEnv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginWSService___LoginDep", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginDepRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strCodAge;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strCodCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strCod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strPass;
        
        public LoginDepRequest() {
        }
        
        public LoginDepRequest(AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader, string strCodAge, string strCodCli, string strCod, string strPass) {
            this.ROClientIDHeader = ROClientIDHeader;
            this.strCodAge = strCodAge;
            this.strCodCli = strCodCli;
            this.strCod = strCod;
            this.strPass = strPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginWSService___LoginDepResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginDepResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strNom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strCodCR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strTipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string strVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string strError;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string strSesion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string strURLDetSegEnv;
        
        public LoginDepResponse() {
        }
        
        public LoginDepResponse(AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader, bool Result, string strNom, string strCodCR, string strTipo, string strVersion, string strError, string strSesion, string strURLDetSegEnv) {
            this.ROClientIDHeader = ROClientIDHeader;
            this.Result = Result;
            this.strNom = strNom;
            this.strCodCR = strCodCR;
            this.strTipo = strTipo;
            this.strVersion = strVersion;
            this.strError = strError;
            this.strSesion = strSesion;
            this.strURLDetSegEnv = strURLDetSegEnv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginWSService___LoginDep2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginDep2Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strCodAge;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strCodCli;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strDepartamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strPass;
        
        public LoginDep2Request() {
        }
        
        public LoginDep2Request(AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader, string strCodAge, string strCodCli, string strDepartamento, string strPass) {
            this.ROClientIDHeader = ROClientIDHeader;
            this.strCodAge = strCodAge;
            this.strCodCli = strCodCli;
            this.strDepartamento = strDepartamento;
            this.strPass = strPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginWSService___LoginDep2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginDep2Response {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strCodAgeOut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strCodCliOut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strCod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string strNom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string strCodCR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string strTipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string strVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string strError;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string strSesion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string strURLDetSegEnv;
        
        public LoginDep2Response() {
        }
        
        public LoginDep2Response(AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader, bool Result, string strCodAgeOut, string strCodCliOut, string strCod, string strNom, string strCodCR, string strTipo, string strVersion, string strError, string strSesion, string strURLDetSegEnv) {
            this.ROClientIDHeader = ROClientIDHeader;
            this.Result = Result;
            this.strCodAgeOut = strCodAgeOut;
            this.strCodCliOut = strCodCliOut;
            this.strCod = strCod;
            this.strNom = strNom;
            this.strCodCR = strCodCR;
            this.strTipo = strTipo;
            this.strVersion = strVersion;
            this.strError = strError;
            this.strSesion = strSesion;
            this.strURLDetSegEnv = strURLDetSegEnv;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginWSServiceChannel : AppUptook.LoginWSService.LoginWSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginWSServiceClient : System.ServiceModel.ClientBase<AppUptook.LoginWSService.LoginWSService>, AppUptook.LoginWSService.LoginWSService {
        
        public LoginWSServiceClient() {
        }
        
        public LoginWSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginWSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginWSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginWSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppUptook.LoginWSService.LoginResponse AppUptook.LoginWSService.LoginWSService.Login(AppUptook.LoginWSService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(ref AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader, string strCod, string strPass, out string strNom, out string strCodAge, out string strCodCR, out string strTipo, out string strVersion, out string strError, out string strSesion, out string strURLDetSegEnv) {
            AppUptook.LoginWSService.LoginRequest inValue = new AppUptook.LoginWSService.LoginRequest();
            inValue.ROClientIDHeader = ROClientIDHeader;
            inValue.strCod = strCod;
            inValue.strPass = strPass;
            AppUptook.LoginWSService.LoginResponse retVal = ((AppUptook.LoginWSService.LoginWSService)(this)).Login(inValue);
            ROClientIDHeader = retVal.ROClientIDHeader;
            strNom = retVal.strNom;
            strCodAge = retVal.strCodAge;
            strCodCR = retVal.strCodCR;
            strTipo = retVal.strTipo;
            strVersion = retVal.strVersion;
            strError = retVal.strError;
            strSesion = retVal.strSesion;
            strURLDetSegEnv = retVal.strURLDetSegEnv;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<AppUptook.LoginWSService.LoginResponse> LoginAsync(AppUptook.LoginWSService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppUptook.LoginWSService.Login2Response AppUptook.LoginWSService.LoginWSService.Login2(AppUptook.LoginWSService.Login2Request request) {
            return base.Channel.Login2(request);
        }
        
        public bool Login2(ref AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader, string strUsuario, string strPass, out string strCod, out string strNom, out string strCodAge, out string strCodCR, out string strTipo, out string strVersion, out string strError, out string strSesion, out string strURLDetSegEnv) {
            AppUptook.LoginWSService.Login2Request inValue = new AppUptook.LoginWSService.Login2Request();
            inValue.ROClientIDHeader = ROClientIDHeader;
            inValue.strUsuario = strUsuario;
            inValue.strPass = strPass;
            AppUptook.LoginWSService.Login2Response retVal = ((AppUptook.LoginWSService.LoginWSService)(this)).Login2(inValue);
            ROClientIDHeader = retVal.ROClientIDHeader;
            strCod = retVal.strCod;
            strNom = retVal.strNom;
            strCodAge = retVal.strCodAge;
            strCodCR = retVal.strCodCR;
            strTipo = retVal.strTipo;
            strVersion = retVal.strVersion;
            strError = retVal.strError;
            strSesion = retVal.strSesion;
            strURLDetSegEnv = retVal.strURLDetSegEnv;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<AppUptook.LoginWSService.Login2Response> Login2Async(AppUptook.LoginWSService.Login2Request request) {
            return base.Channel.Login2Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppUptook.LoginWSService.LoginCliResponse AppUptook.LoginWSService.LoginWSService.LoginCli(AppUptook.LoginWSService.LoginCliRequest request) {
            return base.Channel.LoginCli(request);
        }
        
        public bool LoginCli(ref AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader, string strCodAge, string strCod, string strPass, out string strNom, out string strCodCR, out string strTipo, out string strVersion, out string strError, out string strSesion, out string strURLDetSegEnv) {
            AppUptook.LoginWSService.LoginCliRequest inValue = new AppUptook.LoginWSService.LoginCliRequest();
            inValue.ROClientIDHeader = ROClientIDHeader;
            inValue.strCodAge = strCodAge;
            inValue.strCod = strCod;
            inValue.strPass = strPass;
            AppUptook.LoginWSService.LoginCliResponse retVal = ((AppUptook.LoginWSService.LoginWSService)(this)).LoginCli(inValue);
            ROClientIDHeader = retVal.ROClientIDHeader;
            strNom = retVal.strNom;
            strCodCR = retVal.strCodCR;
            strTipo = retVal.strTipo;
            strVersion = retVal.strVersion;
            strError = retVal.strError;
            strSesion = retVal.strSesion;
            strURLDetSegEnv = retVal.strURLDetSegEnv;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<AppUptook.LoginWSService.LoginCliResponse> LoginCliAsync(AppUptook.LoginWSService.LoginCliRequest request) {
            return base.Channel.LoginCliAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppUptook.LoginWSService.LoginCli2Response AppUptook.LoginWSService.LoginWSService.LoginCli2(AppUptook.LoginWSService.LoginCli2Request request) {
            return base.Channel.LoginCli2(request);
        }
        
        public bool LoginCli2(ref AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader, string strCodAge, string strCliente, string strPass, out string strCodAgeOut, out string strCod, out string strNom, out string strCodCR, out string strTipo, out string strVersion, out string strError, out string strSesion, out string strURLDetSegEnv) {
            AppUptook.LoginWSService.LoginCli2Request inValue = new AppUptook.LoginWSService.LoginCli2Request();
            inValue.ROClientIDHeader = ROClientIDHeader;
            inValue.strCodAge = strCodAge;
            inValue.strCliente = strCliente;
            inValue.strPass = strPass;
            AppUptook.LoginWSService.LoginCli2Response retVal = ((AppUptook.LoginWSService.LoginWSService)(this)).LoginCli2(inValue);
            ROClientIDHeader = retVal.ROClientIDHeader;
            strCodAgeOut = retVal.strCodAgeOut;
            strCod = retVal.strCod;
            strNom = retVal.strNom;
            strCodCR = retVal.strCodCR;
            strTipo = retVal.strTipo;
            strVersion = retVal.strVersion;
            strError = retVal.strError;
            strSesion = retVal.strSesion;
            strURLDetSegEnv = retVal.strURLDetSegEnv;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<AppUptook.LoginWSService.LoginCli2Response> LoginCli2Async(AppUptook.LoginWSService.LoginCli2Request request) {
            return base.Channel.LoginCli2Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppUptook.LoginWSService.LoginDepResponse AppUptook.LoginWSService.LoginWSService.LoginDep(AppUptook.LoginWSService.LoginDepRequest request) {
            return base.Channel.LoginDep(request);
        }
        
        public bool LoginDep(ref AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader, string strCodAge, string strCodCli, string strCod, string strPass, out string strNom, out string strCodCR, out string strTipo, out string strVersion, out string strError, out string strSesion, out string strURLDetSegEnv) {
            AppUptook.LoginWSService.LoginDepRequest inValue = new AppUptook.LoginWSService.LoginDepRequest();
            inValue.ROClientIDHeader = ROClientIDHeader;
            inValue.strCodAge = strCodAge;
            inValue.strCodCli = strCodCli;
            inValue.strCod = strCod;
            inValue.strPass = strPass;
            AppUptook.LoginWSService.LoginDepResponse retVal = ((AppUptook.LoginWSService.LoginWSService)(this)).LoginDep(inValue);
            ROClientIDHeader = retVal.ROClientIDHeader;
            strNom = retVal.strNom;
            strCodCR = retVal.strCodCR;
            strTipo = retVal.strTipo;
            strVersion = retVal.strVersion;
            strError = retVal.strError;
            strSesion = retVal.strSesion;
            strURLDetSegEnv = retVal.strURLDetSegEnv;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<AppUptook.LoginWSService.LoginDepResponse> LoginDepAsync(AppUptook.LoginWSService.LoginDepRequest request) {
            return base.Channel.LoginDepAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppUptook.LoginWSService.LoginDep2Response AppUptook.LoginWSService.LoginWSService.LoginDep2(AppUptook.LoginWSService.LoginDep2Request request) {
            return base.Channel.LoginDep2(request);
        }
        
        public bool LoginDep2(ref AppUptook.LoginWSService.ROClientIDHeader ROClientIDHeader, string strCodAge, string strCodCli, string strDepartamento, string strPass, out string strCodAgeOut, out string strCodCliOut, out string strCod, out string strNom, out string strCodCR, out string strTipo, out string strVersion, out string strError, out string strSesion, out string strURLDetSegEnv) {
            AppUptook.LoginWSService.LoginDep2Request inValue = new AppUptook.LoginWSService.LoginDep2Request();
            inValue.ROClientIDHeader = ROClientIDHeader;
            inValue.strCodAge = strCodAge;
            inValue.strCodCli = strCodCli;
            inValue.strDepartamento = strDepartamento;
            inValue.strPass = strPass;
            AppUptook.LoginWSService.LoginDep2Response retVal = ((AppUptook.LoginWSService.LoginWSService)(this)).LoginDep2(inValue);
            ROClientIDHeader = retVal.ROClientIDHeader;
            strCodAgeOut = retVal.strCodAgeOut;
            strCodCliOut = retVal.strCodCliOut;
            strCod = retVal.strCod;
            strNom = retVal.strNom;
            strCodCR = retVal.strCodCR;
            strTipo = retVal.strTipo;
            strVersion = retVal.strVersion;
            strError = retVal.strError;
            strSesion = retVal.strSesion;
            strURLDetSegEnv = retVal.strURLDetSegEnv;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<AppUptook.LoginWSService.LoginDep2Response> LoginDep2Async(AppUptook.LoginWSService.LoginDep2Request request) {
            return base.Channel.LoginDep2Async(request);
        }
    }
}
